const os=require('os')
console.log(os.arch())
console.log(os.platform())
console.log(os.version())
console.log(os.userInfo())
console.log(os.hostname())
console.log(os.freemem())
console.log(os.totalmem())
console.log(os.cpus())
console.log(os.networkInterfaces())